//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using OOSelenium.Framework.Abstractions;
using OOSelenium.Framework.Entities;
using OOSelenium.Framework.WebUIControls;
using OpenQA.Selenium;


namespace MyApp.MyFunctionality.MyPurpose
{
	
	
	public sealed class OnlineShoppingPage : WebUiPageBase
	{
		
		public Link RefnavLogoLink { get; init; }

		public TextField TwotabsearchtextboxTextField { get; init; }

		public SubmitButton GoSubmitButton { get; init; }

		public Span YourAccountSpan { get; init; }

		public Span YourOrdersSpan { get; init; }

		public Span YourWishListSpan { get; init; }

		public Span ReturnsSpan { get; init; }

		public Span CartSpan { get; init; }

		
		public OnlineShoppingPage(IWebDriver webDriver, String baseUrl) : 
				base(webDriver, baseUrl)
		{
            RefnavLogoLink = base.FindById<Link>("nav-logo-sprites", (id, webElement, webDriver) => new Link (webElement, id, LocateByWhat.Id, webDriver));

            TwotabsearchtextboxTextField = base.FindById<TextField>("twotabsearchtextbox", (id, webElement, webDriver) => new TextField (webElement, id, LocateByWhat.Id, webDriver));

            GoSubmitButton = base.FindById<SubmitButton>("nav-search-submit-button", (id, webElement, webDriver) => new SubmitButton (webElement, id, LocateByWhat.Id, webDriver));

            YourAccountSpan = base.FindByXPath<Span>("id(\"nav-al-your-account\")/ul/li/a/span", (xPath, webElement, webDriver) => new Span (webElement, xPath, LocateByWhat.XPath, webDriver));

            YourOrdersSpan = base.FindByXPath<Span>("id(\"nav_prefetch_yourorders\")/span", (xPath, webElement, webDriver) => new Span (webElement, xPath, LocateByWhat.XPath, webDriver));

            YourWishListSpan = base.FindByXPath<Span>("id(\"nav-al-your-account\")/ul/li[3]/a/span", (xPath, webElement, webDriver) => new Span (webElement, xPath, LocateByWhat.XPath, webDriver));

            ReturnsSpan = base.FindByXPath<Span>("id(\"nav-orders\")/span", (xPath, webElement, webDriver) => new Span (webElement, xPath, LocateByWhat.XPath, webDriver));

            CartSpan = base.FindByXPath<Span>("id(\"nav-cart-text-container\")/span[2]", (xPath, webElement, webDriver) => new Span (webElement, xPath, LocateByWhat.XPath, webDriver));
		}
	}
}
