//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using OOSelenium.Framework.Abstractions;
using OOSelenium.Framework.Entities;
using OOSelenium.Framework.WebUIControls;
using OpenQA.Selenium;


namespace OOSelenium.WebUiTests.LetsKodeTests.Pages
{
	
	
	public sealed class LetsKodeItPracticePage : WebUiPageBase
	{
		
		private RadioButtons _carsRadioButtons;
		
		private DropDownList _carsDropDownList;
		
		private MultiSelectListBox _fruitsMultiSelectListBox;
		
		private CheckBox _bmwCheckBox;
		
		private CheckBox _benzCheckBox;
		
		private CheckBox _hondaCheckBox;
		
		public LetsKodeItPracticePage(IWebDriver webDriver, String baseUrl, bool navigationRequired, bool maximizeWindow) : 
				base(webDriver, baseUrl, navigationRequired, maximizeWindow)
		{
		}
		
		public RadioButtons CarsRadioButtons
		{
			get
			{
				// 
				// Other available X-paths:
				// 
				/// X-path by 'id' : //*[@id='bmwradio']
				/// X-path by 'data-testid' : 
				/// X-path by 'name' : //*[@name='cars']
				/// X-path by 'class' : 
				// 
				if ((_carsRadioButtons == null))
				{
	_carsRadioButtons = base.FindRadioButtonGroupByName("cars");
				}
				return _carsRadioButtons;
			}
		}
		
		public DropDownList CarsDropDownList
		{
			get
			{
				// 
				// Other available X-paths:
				// 
				/// X-path by 'id' : //*[@id='carselect']
				/// X-path by 'data-testid' : 
				/// X-path by 'name' : //*[@name='cars']
				/// X-path by 'class' : 
				// 
				if ((_carsDropDownList == null))
				{
	_carsDropDownList = base.FindDropDownListByXPath("/html/body/div/div[2]/div[2]/div/div/div/div/div[2]/div/fieldset/select");
				}
				return _carsDropDownList;
			}
		}
		
		public MultiSelectListBox FruitsMultiSelectListBox
		{
			get
			{
				// 
				// Other available X-paths:
				// 
				/// X-path by 'id' : 
				/// X-path by 'data-testid' : 
				/// X-path by 'name' : 
				/// X-path by 'class' : 
				// 
				if ((_fruitsMultiSelectListBox == null))
				{
	_fruitsMultiSelectListBox = base.FindMultiSelectListBoxByXPath("/html/body/div/div[2]/div[2]/div/div/div/div/div[2]/div[2]/fieldset/select");


				}
				return _fruitsMultiSelectListBox;
			}
		}
		
		public CheckBox BmwCheckBox
		{
			get
			{
				// 
				// Other available X-paths:
				// 
				/// X-path by 'id' : //*[@id='bmwcheck']
				/// X-path by 'data-testid' : 
				/// X-path by 'name' : //*[@name='cars']
				/// X-path by 'class' : 
				// 
				if ((_bmwCheckBox == null))
				{
	_bmwCheckBox = base.FindByXPath<CheckBox>("/html/body/div/div[2]/div[2]/div/div/div/div/div/div[2]/fieldset/label/input", (xPath, webElement, webDriver) => new CheckBox(webElement, xPath, LocateByWhat.XPath, webDriver));
				}
				return _bmwCheckBox;
			}
		}
		
		public CheckBox BenzCheckBox
		{
			get
			{
				// 
				// Other available X-paths:
				// 
				/// X-path by 'id' : //*[@id='benzcheck']
				/// X-path by 'data-testid' : 
				/// X-path by 'name' : //*[@name='cars']
				/// X-path by 'class' : 
				// 
				if ((_benzCheckBox == null))
				{
	_benzCheckBox = base.FindByXPath<CheckBox>("/html/body/div/div[2]/div[2]/div/div/div/div/div/div[2]/fieldset/label[2]/input", (xPath, webElement, webDriver) => new CheckBox(webElement, xPath, LocateByWhat.XPath, webDriver));
				}
				return _benzCheckBox;
			}
		}
		
		public CheckBox HondaCheckBox
		{
			get
			{
				// 
				// Other available X-paths:
				// 
				/// X-path by 'id' : //*[@id='hondacheck']
				/// X-path by 'data-testid' : 
				/// X-path by 'name' : //*[@name='cars']
				/// X-path by 'class' : 
				// 
				if ((_hondaCheckBox == null))
				{
	_hondaCheckBox = base.FindByXPath<CheckBox>("/html/body/div/div[2]/div[2]/div/div/div/div/div/div[2]/fieldset/label[3]/input", (xPath, webElement, webDriver) => new CheckBox(webElement, xPath, LocateByWhat.XPath, webDriver));
				}
				return _hondaCheckBox;
			}
		}
	}
}
