//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using OOSelenium.Framework.Abstractions;
using OOSelenium.Framework.Entities;
using OOSelenium.Framework.WebUIControls;
using OpenQA.Selenium;


namespace OOSelenium.WebUiTests.OtherTests.Pages
{
	
	
	public sealed class CommBankPage : WebUiPageBase
	{
		
		public Span SearchLensSpan { get; init; }

		
		public CommBankPage(IWebDriver webDriver, String baseUrl) : 
				base(webDriver, baseUrl)
		{
            SearchLensSpan = base.FindByXPath<Span>("id(\"skipsearch\")/span", (xPath, webElement, webDriver) => new Span (webElement, xPath, LocateByWhat.XPath, webDriver));

		}
		
		public TextField SearchTextField
		{
			get
			{
				return base.FindById<TextField>("header-search-input-box", (id, webElement, webDriver) => new TextField(webElement, id, LocateByWhat.Id, webDriver));
			}
		}
		
		public Link BankLoanLink
		{
			get
			{
				return base.FindByXPath<Link>("id(\"searchModal\")/div[3]/div/ul/li/a", (xPath, webElement, webDriver) => new Link(webElement, xPath, LocateByWhat.XPath, webDriver));
			}
		}
	}
}
