//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using OOSelenium.Framework.Abstractions;
using OOSelenium.Framework.Entities;
using OOSelenium.Framework.WebUIControls;
using OpenQA.Selenium;


namespace OOSelenium.WebUiTests.TestWebAppTests.Pages
{
	
	
	public sealed class InsuranceOneLoginPage : WebUiPageBase
	{
		
		private ValidationSummary _validationSummary;
		
		private Image _applicationLogoImage;
		
		private Label _userIdLabel;
		
		private TextField _userIdTextField;
		
		private Label _passwordLabel;
		
		private TextField _passwordTextField;
		
		private SubmitButton _signInSubmitButton;
		
		public InsuranceOneLoginPage(IWebDriver webDriver, string baseUrl, bool navigationRequired, bool maximizeWindow) : 
				base(webDriver, baseUrl, navigationRequired, maximizeWindow)
		{
		}
		
		public ValidationSummary ValidationSummary
		{
			get
			{
				// 
				// Other available X-paths:
				// 
				/// X-path by 'id' : 
				/// X-path by 'data-testid' : 
				/// X-path by 'name' : 
				/// X-path by 'class' : 
				// 
				if ((_validationSummary == null))
				{
	_validationSummary = base.FindByXPath<ValidationSummary>("/html/body/form/div/div", (xPath, webElement, webDriver) => new ValidationSummary(webElement, xPath, LocateByWhat.XPath, webDriver));
				}
				return _validationSummary;
			}
		}
		
		public Image ApplicationLogoImage
		{
			get
			{
				// 
				// Other available X-paths:
				// 
				/// X-path by 'id' : //*[@id='applicationLogo']
				/// X-path by 'data-testid' : 
				/// X-path by 'name' : 
				/// X-path by 'class' : 
				// 
				if ((_applicationLogoImage == null))
				{
	_applicationLogoImage = base.FindByXPath<Image>("/html/body/form/div/img", (xPath, webElement, webDriver) => new Image(webElement, xPath, LocateByWhat.XPath, webDriver));
				}
				return _applicationLogoImage;
			}
		}
		
		public Label UserIdLabel
		{
			get
			{
				// 
				// Other available X-paths:
				// 
				/// X-path by 'id' : //*[@id='userIdLabel']
				/// X-path by 'data-testid' : 
				/// X-path by 'name' : 
				/// X-path by 'class' : //*[contains(concat(' ', normalize-space(@class), ' '), ' col-md-8 ')] | //*[contains(concat(' ', normalize-space(@class), ' '), ' text-right ')]
				// 
				if ((_userIdLabel == null))
				{
	_userIdLabel = base.FindByXPath<Label>("/html/body/form/div/div[2]/table/tbody/tr/td/label", (xPath, webElement, webDriver) => new Label(webElement, xPath, LocateByWhat.XPath, webDriver));
				}
				return _userIdLabel;
			}
		}
		
		public TextField UserIdTextField
		{
			get
			{
				// 
				// Other available X-paths:
				// 
				/// X-path by 'id' : //*[@id='userIdField']
				/// X-path by 'data-testid' : 
				/// X-path by 'name' : //*[@name='UserId']
				/// X-path by 'class' : //*[contains(concat(' ', normalize-space(@class), ' '), ' form-control ')] | //*[contains(concat(' ', normalize-space(@class), ' '), ' text-box ')] | //*[contains(concat(' ', normalize-space(@class), ' '), ' single-line ')]
				// 
				if ((_userIdTextField == null))
				{
	_userIdTextField = base.FindByXPath<TextField>("/html/body/form/div/div[2]/table/tbody/tr/td[2]/input", (xPath, webElement, webDriver) => new TextField(webElement, xPath, LocateByWhat.XPath, webDriver));
				}
				return _userIdTextField;
			}
		}
		
		public Label PasswordLabel
		{
			get
			{
				// 
				// Other available X-paths:
				// 
				/// X-path by 'id' : //*[@id='passwordLabel']
				/// X-path by 'data-testid' : 
				/// X-path by 'name' : 
				/// X-path by 'class' : //*[contains(concat(' ', normalize-space(@class), ' '), ' col-md-8 ')] | //*[contains(concat(' ', normalize-space(@class), ' '), ' text-right ')]
				// 
				if ((_passwordLabel == null))
				{
	_passwordLabel = base.FindByXPath<Label>("/html/body/form/div/div[2]/table/tbody/tr[2]/td/label", (xPath, webElement, webDriver) => new Label(webElement, xPath, LocateByWhat.XPath, webDriver));
				}
				return _passwordLabel;
			}
		}
		
		public TextField PasswordTextField
		{
			get
			{
				// 
				// Other available X-paths:
				// 
				/// X-path by 'id' : //*[@id='passwordField']
				/// X-path by 'data-testid' : 
				/// X-path by 'name' : //*[@name='EncryptedPassword']
				/// X-path by 'class' : //*[contains(concat(' ', normalize-space(@class), ' '), ' form-control ')]
				// 
				if ((_passwordTextField == null))
				{
	_passwordTextField = base.FindByXPath<TextField>("/html/body/form/div/div[2]/table/tbody/tr[2]/td[2]/input", (xPath, webElement, webDriver) => new TextField(webElement, xPath, LocateByWhat.XPath, webDriver));
				}
				return _passwordTextField;
			}
		}
		
		public SubmitButton SignInSubmitButton
		{
			get
			{
				// 
				// Other available X-paths:
				// 
				/// X-path by 'id' : //*[@id='signInButton']
				/// X-path by 'data-testid' : 
				/// X-path by 'name' : 
				/// X-path by 'class' : //*[contains(concat(' ', normalize-space(@class), ' '), ' btn ')] | //*[contains(concat(' ', normalize-space(@class), ' '), ' btn-primary ')]
				// 
				if ((_signInSubmitButton == null))
				{
	_signInSubmitButton = base.FindByXPath<SubmitButton>("/html/body/form/div/div[2]/table/tbody/tr[3]/td[2]/input", (xPath, webElement, webDriver) => new SubmitButton(webElement, xPath, LocateByWhat.XPath, webDriver));
				}
				return _signInSubmitButton;
			}
		}
	}
}
